sudo: false
language: node_js
cache:
  directories:
    - node_modules
# branches:
#   only:
#     - main
#     - develop
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm test
